import Head from 'next/head'
import Feed from '../components/feed'
import Sidebar from '../components/sidebar'
import Wedjet from '../components/Wedjet'





export default function Home({newresult}) {
  return (
    <>
      <Head>
        <title>twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>
{/* side bar */}

<Sidebar />

{/* feed  */}
<Feed />
{/* wedjets */}
<Wedjet newresult={newresult.articles} />
{/* modal */}


      </main>
      
    </>
  )
}
export async function getServerSideProps(){
  const newresult =await fetch("https://saurav.tech/NewsAPI/top-headlines/category/technology/in.json").then((res)=>res.json())
  return{
      props:{
          newresult,
      }
  }
}
