import Head from 'next/head'
import Feed from '../components/feed'
import Sidebar from '../components/sidebar'
import Wedjet from '../components/Wedjet'





export default function Home() {
  return (
    <>
      <Head>
        <title>twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>
{/* side bar */}

<Sidebar />

{/* feed  */}
<Feed />
{/* wedjets */}
<Wedjet />
{/* modal */}


      </main>
      
    </>
  )
}
