import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'




export default function Home() {
  return (
    <>
      <Head>
        <title>twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='font-medium size-lg text-center'>hello world</h1>
      
    </>
  )
}
